function getSkills() {
    return [
        {
            name: "(No Skill)",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Agility Training",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Beat Up",
            type: "Normal",
            power: 20,
            atkType: "Physical",
        },
        {
            name: "Body Blast",
            type: "Heavy",
            power: 100,
            atkType: "Physical",
        },
        {
            name: "Boulder Barrage",
            type: "Sand",
            power: 65,
            atkType: "Physical",
        },
        {
            name: "Bubble Burst",
            type: "Water",
            power: 40,
            atkType: "Special",
        },
        {
            name: "Chomp",
            type: "Foul",
            power: 40,
            atkType: "Physical",
        },
        {
            name: "Cinder",
            type: "Fire",
            power: 40,
            atkType: "Special"
        },
        {
            name: "Claw",
            type: "Cut",
            power: 40,
            atkType: "Physical",
        },
        {
            name: "Clearing Wind",
            type: "Ice",
            power: 60,
            atkType: "Special",
        },
        {
            name: "Coin Snatch",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Concentrate",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Constrict",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Crystal Surprise",
            type: "Water",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Cute Pose",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Disable",
            type: "Magic",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Distract",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Double Slash",
            type: "Cut",
            power: 75,
            atkType: "Physical",
        },
        {
            name: "Double Sting",
            type: "Normal",
            power: 30,
            atkType: "Physical",
        },
        {
            name: "Drain",
            type: "Magic",
            power: 40,
            atkType: "Special",
        },
        {
            name: "Electric Pound",
            type: "Electric",
            power: 20,
            atkType: "Physical",
        },
        {
            name: "Electrify",
            type: "Electric",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Energy Drain",
            type: "Magic",
            power: 40,
            atkType: "Special",
        },
        {
            name: "Epiphany",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Face Slap",
            type: "Normal",
            power: 60,
            atkType: "Physical",
        },
        {
            name: "Factory Reset",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Fade Attack",
            type: "Foul",
            power: 50,
            atkType: "Physical",
        },
        {
            name: "Fast Strike",
            type: "Normal",
            power: 40,
            atkType: "Physical",
        },
        {
            name: "Feelers",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Feint Spurts",
            type: "Water",
            power: 65,
            atkType: "Special",
        },
        {
            name: "Final Gift",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Frost Chomp",
            type: "Ice",
            power: 40,
            atkType: "Physical",
        },
        {
            name: "Frost Web",
            type: "Ice",
            power: 40,
            atkType: "Status",
        },
        {
            name: "Glacier",
            type: "Ice",
            power: 80,
            atkType: "Special",
        },
        {
            name: "Howl",
            type: "Ghost",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Hypno Wave",
            type: "Ghost",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Ice Wall",
            type: "Ice",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Ignite",
            type: "Fire",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Ignore Pain",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Last Stand",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Lightning Strike",
            type: "Electric",
            power: 60,
            atkType: "Special",
        },
        {
            name: "Mighty Roar",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Piercing Horns",
            type: "Fire",
            power: 60,
            atkType: "Physical",
        },
        {
            name: "Pocket Sand",
            type: "Sand",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Poison Chomp",
            type: "Poison",
            power: 80,
            atkType: "Physical",
        },
        {
            name: "Poison Sting",
            type: "Poison",
            power: 20,
            atkType: "Physical",
        },
        {
            name: "Power Slap",
            type: "Electric",
            power: 30,
            atkType: "Physical",
        },
        {
            name: "Power Talons",
            type: "Electric",
            power: 90,
            atkType: "Physical",
        },
        {
            name: "Precision Eye",
            type: "Electric",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Propellor Punch",
            type: "Normal",
            power: 50,
            atkType: "Physical",
        },
        {
            name: "Quad Volt",
            type: "Electric",
            power: 55,
            atkType: "Special",
        },
        {
            name: "Quick Charge",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Rage",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Sandball",
            type: "Sand",
            power: 40,
            atkType: "Special",
        },
        {
            name: "Sandman",
            type: "Sand",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Scratch",
            type: "Cut",
            power: 40,
            atkType: "Physical",
        },
        {
            name: "Shadewalker",
            type: "Ghost",
            power: 40,
            atkType: "Physical",
        },
        {
            name: "Slam",
            type: "Normal",
            power: 40,
            atkType: "Physical",
        },
        {
            name: "Smokescreen",
            type: "Fire",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Spark Disc",
            type: "Electric",
            power: 50,
            atkType: "Physical",
        },
        {
            name: "Spark Wall",
            type: "Electric",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Splash",
            type: "Water",
            power: 0,
            atkType: "Special",
        },
        {
            name: "Static Fur",
            type: "Electric",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Streamline",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Super Punch",
            type: "Electric",
            power: 160,
            atkType: "Physical",
        },
        {
            name: "Surge Punch",
            type: "Electric",
            power: 70,
            atkType: "Special",
        },
        {
            name: "Swarm Diversion",
            type: "Electric",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Tail Spin",
            type: "Normal",
            power: 25,
            atkType: "Physical",
        },
        {
            name: "Taser",
            type: "Electric",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Toughen Up",
            type: "Normal",
            power: 0,
            atkType: "Status",
        },
        {
            name: "Venomous Bees",
            type: "Poison",
            power: 30,
            atkType: "Special",
        },
        {
            name: "Voodoo",
            type: "Magic",
            power: 70,
            atkType: "Special",
        },
        {
            name: "Wind Blast",
            type: "Air",
            power: 85,
            atkType: "Special",
        }
    ];
}